### ISSUE TITLE
http example config

### ISSUE THREAD

**Issue by zcy382725** [untergeek/es_client#42]
```
---
elasticsearch:
  client:
    hosts: http://10.19.31.139:9200
    cloud_id:
    bearer_auth:
    opaque_id:
    request_timeout: 60
    http_compress:
    verify_certs: 
    ca_certs:
    client_cert:
    client_key:
    ssl_assert_hostname:
    ssl_assert_fingerprint:
    ssl_version:
  other_settings:
    master_only: False
    skip_version_test: True
    username: elastic
    password: asdasdawasdasda
    api_key:
      id:
      api_key:

logging:
  loglevel: DEBUG
  logfile:
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']


``` 
Failed using this config to establish connection with a http end elasticsearch.
